version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  kafka-topics:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c", " \
      until /usr/bin/kafka-topics --bootstrap-server kafka:9092 --list; do sleep 0.1; done; \
      /usr/bin/kafka-topics --bootstrap-server kafka:9092 --create --topic parce-video-topic --partitions 1 --replication-factor 1; \
      /usr/bin/kafka-topics --bootstrap-server kafka:9092 --create --topic download-video-topic --partitions 1 --replication-factor 1; \
      /usr/bin/kafka-topics --bootstrap-server kafka:9092 --create --topic video-to-image-topic --partitions 1 --replication-factor 1; \
      /usr/bin/kafka-topics --bootstrap-server kafka:9092 --create --topic video-to-audio-topic --partitions 1 --replication-factor 1; \
      /usr/bin/kafka-topics --bootstrap-server kafka:9092 --create --topic audio-to-text-topic --partitions 1 --replication-factor 1; \
      /usr/bin/kafka-topics --bootstrap-server kafka:9092 --create --topic video-topic --partitions 1 --replication-factor 3; \
      /usr/bin/kafka-topics --bootstrap-server kafka:9092 --create --topic text-topic --partitions 1 --replication-factor 3; \
      /usr/bin/kafka-topics --bootstrap-server kafka:9092 --create --topic final-ml-topic --partitions 1 --replication-factor 1; \
      "]

  producer:
    build: ./producer
    depends_on:
      - kafka
      - kafka-topics
      - consumer

  consumer:
    build: ./consumer
    restart: always
    depends_on:
      - kafka

  parce-video-page:
    build: ./parce-video-page
    restart: on-failure
    depends_on:
      - kafka