apiVersion: v1
kind: Pod
metadata:
  name: kaniko-producer
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=/workspace/Dockerfile"
    - "--context=dir://workspace"
    - "--destination=producer:latest"
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  restartPolicy: Never
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: workspace-pvc